# Generated by Django 5.2.7 on 2025-12-30 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-update', '-created']},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['-update', '-created']},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-update', '-created']},
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['-update', '-created']},
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('equipos_count', models.IntegerField(default=0)),
                ('tareas_completadas', models.IntegerField(default=0)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
