# Generated by Django 5.2.7 on 2025-12-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_comentario_options_alter_equipo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
