# Generated by Django 5.2.7 on 2025-12-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_perfil_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='equipos_count',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='tareas_completadas',
        ),
    ]
