# Generated by Django 5.2.7 on 2025-12-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_perfil_equipos_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En_progreso'), ('completada', 'Completada'), ('pausada', 'Pausada')], default='pendiente', max_length=20),
        ),
    ]
