# Generated by Django 5.2.7 on 2026-01-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_comentario_options_tarea_fecha_limite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('trabajo', 'Trabajo')], max_length=20, null=True),
        ),
    ]
