# Generated by Django 5.2.7 on 2026-01-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_proyecto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(choices=[('personal', 'Personal'), ('trabajo', 'Trabajo')], max_length=20),
        ),
    ]
