# Generated by Django 5.2.7 on 2026-01-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_proyecto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='pais',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(blank=True, default='usuario', max_length=50, null=True),
        ),
    ]
