# Generated by Django 5.2.7 on 2026-01-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_perfil_pais_perfil_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='numero',
            field=models.CharField(blank=True, default='No registrado', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='pais',
            field=models.CharField(blank=True, default='No registrado', max_length=20, null=True),
        ),
    ]
