# Generated by Django 5.2.7 on 2026-01-02 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_perfil_numero_alter_perfil_pais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='update',
            new_name='updated',
        ),
    ]
